# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-27 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20180212_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='meal_choice',
            field=models.CharField(choices=[('PM', 'Meal Planned'), ('CM', 'Consumed Meal')], default='PM', max_length=2),
        ),
    ]
