# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180212_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_use_api_to_create_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
