# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-07 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_workoutlog_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='use_periodization',
            field=models.BooleanField(default=False, help_text='Tick the box if you want to use periodized schedules ', verbose_name='Use periodization'),
        ),
    ]
