# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-08 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_schedule_use_periodization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestep',
            name='duration',
            field=models.IntegerField(default=4, help_text='The duration in weeks', verbose_name='Duration'),
        ),
    ]
