# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-08 13:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20180308_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='use_periodization',
        ),
        migrations.AlterField(
            model_name='schedulestep',
            name='duration',
            field=models.IntegerField(default=4, help_text='The duration in weeks', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='Duration'),
        ),
    ]
