# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-08 14:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20180308_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='use_periodization',
            field=models.BooleanField(default=False, help_text='Tick the box if you want to use periodized schedules ', verbose_name='Use periodization'),
        ),
        migrations.AlterField(
            model_name='schedulestep',
            name='duration',
            field=models.IntegerField(default=4, help_text='The duration in weeks', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Duration'),
        ),
    ]
